name: Mein erster Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Rust installieren
        uses: dtolnay/rust-toolchain@stable

      - name: Abhängigkeiten installieren
        run: npm ci

      
      #- name: Tauri App bauen
       # uses: tauri-apps/tauri-action@v0
        #env:
         # TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY}}
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD}}
        
      - name: SSH vorbereiten
        env:
          SSH_PRIV: ${{ secrets.HETZER_LOGIN }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_PRIV" > ~/.ssh/hetzner_deploy
          chmod 600 ~/.ssh/hetzner_deploy
          ssh-keyscan -H 178.104.161.110 >> ~/.ssh/known_hosts
          
      - name: hetzner login 
        env:
          HETZNER_HOST: ${{ vars.HETZNER_HOST }}
          HETZNER_USER: ${{ vars.HETZNER_USER }}
        run: |
          ssh -i ~/.ssh/hetzner_deploy \
          deploy-tester@178.104.161.110 \
          "whoami"
      
      - name: json automatisch erzeugen 
        run: | 
          node -e '
            const fs = require("fs") 
            const daten = {
              version: "0.2.3",
              name: "Updater"
            }
            const json = JSON.stringify(daten, null, 2);
              fs.writeFileSync("latest.json", json) 
          '
          cat latest.json   
      
